export const contactFormData = [
  {
    id: 1,
    subtitle: "Get in Touch",
    title: "Contact Us Today",
    buttonText: "Submit",
    fullName: "John Doe",
    number: "+1-234-567-8901",
    email: "john.doe@example.com",
    inquiryType: "Admission",
    message: "I would like to know more about the admission process.",
    originPage: "Homepage",
    image: null, // Replace with File object or image URL if needed
  },
  {
    id: 2,
    subtitle: "Ask Us",
    title: "We're Here to Help",
    buttonText: "Send Message",
    fullName: "Jane Smith",
    number: "+44-20-7946-0958",
    email: "jane.smith@example.com",
    inquiryType: "Courses",
    message: "Can you provide a list of available courses?",
    originPage: "Courses Page",
    image: null,
  },
  {
    id: 3,
    subtitle: "Support",
    title: "Need Help?",
    buttonText: "Contact",
    fullName: "Alex Johnson",
    number: "+91-9876543210",
    email: "alex.j@example.com",
    inquiryType: "Support",
    message: "I’m having trouble logging into my account.",
    originPage: "Support Page",
    image: null,
  },
];